alias C='CUDA_VISIBLE_DEVICES'
alias nvd='nvidia-smi'
alias n2='nvidia-smi -l 2'
alias pins='pip install'
alias p='python'

alias ins='apt install '
alias cp='cp -r'
alias d='rm -rf'
alias xtar='tar -xvf '
alias ztar='tar -zcvf '
alias ctar='tar -cvf '
alias c='chown -R 1000 ~/ld & chown -R 1000 ~/ld '

alias bak='cp ~/.bash_aliases ~/bashrc && cp -r ~/.pip ~/bashrc && cp ~/.vimrc ~/bashrc '
alias vv='vim /etc/vim/vimrc'
alias v='vim'
alias vb='vim ~/.bash_aliases'
alias vbr='vim ~/.bashrc'
alias sb='source ~/.bash_aliases'

alias gs='git status'
alias gb='git branch'
alias gc='git checkout'
alias ga='git add -f'
alias gcm='git commit -m '
alias gp='git pull '

alias q='cd ..'
alias qq='cd ../../'
alias qqq='cd ../../../'
alias qqqq='cd ../../../../'
alias qqqqq='cd ../../../../../'
