alias C='CUDA_VISIBLE_DEVICES'
alias nvd='nvidia-smi'
alias pins='pip install'
alias ins='apt install '
alias n='nvidia-smi'
alias cp='cp -r'
alias p='python'
alias d='rm -rf'
alias bak='cp ~/.bash_aliases ~/bashrc && cp -r ~/.pip ~/bashrc && cp ~/.vimrc ~/bashrc '

alias vv='vim /etc/vim/vimrc'
alias v='vim'
alias vb='vim ~/.bash_aliases'
alias vbr='vim ~/.bashrc'
alias sb='source ~/.bash_aliases'

alias gs='git status'
alias gb='git branch'
alias gc='git checkout'
alias ga='git add -f'
alias gcm='git commit -m '
alias gp='git pull '

alias q='cd ..'
alias qq='cd ../../'
alias qqq='cd ../../../'
alias qqqq='cd ../../../../'
alias qqqqq='cd ../../../../../'
